# Generated by Django 4.0.1 on 2022-01-12 18:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0005_alter_room_options_room_votes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.RemoveField(
            model_name='room',
            name='votes',
        ),
        migrations.AddField(
            model_name='room',
            name='voters',
            field=models.ManyToManyField(blank=True, related_name='voters', to=settings.AUTH_USER_MODEL),
        ),
    ]
