# Generated by Django 4.0.1 on 2022-01-13 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_room_options_remove_room_votes_room_voters'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='link',
            field=models.CharField(default='Some Error Occured', max_length=500),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(default='Some Error Occured', max_length=200),
        ),
    ]
