# Generated by Django 4.0.1 on 2022-01-13 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_room_link_alter_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='link',
            field=models.CharField(max_length=500),
        ),
    ]
