# Generated by Django 4.0.1 on 2022-01-13 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_room_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='link',
            field=models.CharField(default='Some Error Occured', max_length=500),
        ),
    ]
